# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "client" do |client|
    client.vm.box = "centos-base"
    client.vm.box_url = "https://s3.amazonaws.com/rhcsa/centos-base.box"
    client.vm.hostname = "client"
    client.vm.network :private_network, ip: "172.19.20.22"
    client.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
        # Customize the amount of memory on the VM:
      vb.memory = "512"
    end
  end

  config.vm.define "server" do |server|
    server.vm.box = "centos-base"
    server.vm.box_url = "https://s3.amazonaws.com/rhcsa/centos-base.box"
    server.vm.hostname = "server"
    server.vm.network :private_network, ip: "172.19.20.21"
    server.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
        # Customize the amount of memory on the VM:
      vb.memory = "512"
    end
    server.vm.provision "puppet" do |puppet|
      puppet.manifest_file = "server.pp"
    end
  end
end
